version: '3.9'

services:
  db-postgresql:
    image: postgres:latest
    container_name: db-postgresql
    volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    hostname: db-postgresql
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinhadb
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '1GB'