POST http://localhost:8080/pessoas
Content-Type: application/json

{"nickname": "cintra2", "name": "dasd", "birthDate": "1980-09-20", "stack": ["Java", "Ruby"]}

###
GET http://localhost:8080/pessoas/0f48fb5b-3210-4a4c-8c54-58ff94ece833
Accept: application/json
```

###
GET http://localhost:8080/contagem-pessoas
Accept: application/json
```

###
GET http://localhost:8080/pessoas?t=intr
Accept: application/json
```